### PR TITLE
Add address validation function

### LINKED ISSUE #55: PSK/address validation
#### Summary
Currently, it is not possible to validate PSKs or addresses through this library. For clients, like the web wallet, it would be nice if they could reject transferring to "randomAddressThatDoesNotAdhereToOurFormat".

#### Possible solution design or implementation
We can either opt to use one of the lower level cryptographic libraries to verify if the PSK is on a curve, or we can provide a validation function that checks if the PSK is the proper length and base58 encoded.

### PR DESCRIPTION
**Pull request by HDauven**
Resolves #55

### CODE REVIEW

**Review by Daksh14 — CHANGES_REQUESTED** [review]
Should be done on the wasm side where our existing infra lies for creating and validating `PublicSpendKeys` through dusk_pki or similar crate

**Comment by moCello** [comment]
I don't know how we can introduce this check on the wasm side, but I know that during the deprecation of `dusk-pki`, the `PublicSpendKey` moved to `phoenix-core` and is now called `PublicKey`.
I wouldn't want to introduce this check in phoenix-core though, since to me it seems that this check is about validating user-input and this shouldn't be the responsibility of the underlying protocol.

**Comment by Daksh14** [comment]
After @moCello latest commit then I'm ok with the change, need some unit tests for it and we'll be good to go

**Comment by ZER0** [comment]
I will close this PR since we don't want to have this kind of code here.

1. Addresses are contracts' responsibility (and the driver for the wallet), not this library.
2. If we want to provide client-side validation it has therefore to be done in the driver side (wasm)
3. `phoenix-core` already has such validation and indeed a better one compare to this one: here we do not check if the address is a *valid* address for the transfer / phoenix contract, we just check if the characters are correct, but that is not enough. Basically the `PublicKey` of `phoenix-core` can be created from bytes, and if it's not a valid representation it throws. That's more than enough for the driver to perform a "validation".

I will keep the issue open, but close the PR, and we won't address it until we refactor the `dusk-wallet-js` and `wallet-core` properly.

**Pull request closed without merging**
